apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-docker-compose-v2
  name: react-docker-compose-v2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-docker-compose-v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react-docker-compose-v2
    spec:
      containers:
        - image: gcr.io/sixth-edition-102118/react-docker-compose:v2
          imagePullPolicy: IfNotPresent
          name: react-docker-compose
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-docker-compose-v2
  name: react-docker-compose-v2-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: react-docker-compose-v2
  type: LoadBalancer
